version: '3.8'

services:
  backend:
    build:
      context: .
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - HF_TOKEN=${HF_TOKEN}
    volumes:
      - ./data:/app/data  # Optional: To persist uploaded files
    command: uvicorn app:app --host 0.0.0.0 --port 8000

  frontend:
    image: python:3.12.6-slim
    container_name: frontend
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    command: >
      bash -c "
        pip install streamlit &&
        streamlit run frontend.py --server.port=8501
        "